// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your cod
		int N = Integer.parseInt(args[0]);

		int greaterThan = 0; 
		int lessThanOrEqual = 0;

		for (int i = 0; i < N; i++) {
   		 double randomNumber = Math.random();

   		 if (randomNumber > 0.5) {
        greaterThan++;
   		
		} else {
        lessThanOrEqual++;
   		 }
			}


			 System.out.println("> 0.5: " + greaterThan + " times");
			 System.out.println("<= 0.5: " + lessThanOrEqual + " times");
			 

			
			 if (lessThanOrEqual == 0) {
			 } else {
				double TestRandom = (greaterThan / lessThanOrEqual);
				System.out.println("Ratio: " + TestRandom);
			 }

			}
		}
